# Generated by Django 3.0.2 on 2020-03-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=10)),
                ('has_food', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('number_of_players', models.CharField(max_length=10)),
                ('condition', models.CharField(choices=[('1', 'Unplayable'), ('2', 'Poor'), ('3', 'Acceptable'), ('4', 'Good'), ('5', 'Excellent')], default='1', max_length=1)),
                ('comments', models.TextField(max_length=250)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
