# Generated by Django 3.0.2 on 2020-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='has_food',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
