# Generated by Django 3.0.2 on 2020-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='price_range',
            field=models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], default='1', max_length=1),
        ),
    ]
