# Generated by Django 3.0.2 on 2020-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bar_has_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='condition',
            field=models.CharField(choices=[('1', 'Unplayable'), ('2', 'Poor'), ('3', 'Acceptable'), ('4', 'Good'), ('5', 'Excellent')], default='1', max_length=1),
        ),
    ]
